const content = {
    BG: {
        addNewActivityTitle: "Добавяне на фирма",
        categoryLabel: "Избери категория",
        businessTitleLabel: "Наименование на английски език",
        businessTitleBGLabel: "Наименование на български език",
        businessDescriptionLabel: "Описание на английски език",
        businessDescriptionBGLabel: "Описание на български език",
        startedDateLabel: "Дата на стартиране на бизнеса",
        websiteLabel: "Уебсайт",
        emailLabel: "Имейл",
        addImagesLabel: "Прикачи снимки",
        addressLabel: "Адрес",
        mobilePhoneLabel: "Мобилен телефон",
        phoneLabel: "Друг телефон",
        workTimeLabel: "Работно време",
        addWorkTimeLabel: "Добави ново време",
        dayLabel: "Ден",
        selectDayLabel: "Избери ден",
        timeRangeLabel: "Диапазон",
        startTimeRangeLabel: "Начален час",
        endTimeRangeLabel: "Краен час",
    },
    ENG: {
        addNewActivityTitle: "Add new company",
        categoryLabel: "Select category",
        businessTitleLabel: "Company name with english characters",
        businessTitleBGLabel: "Company name with bulgarian characters",
        businessDescriptionLabel: "Company description with english characters",
        businessDescriptionBGLabel: "Company description with bulgarian characters",
        startedDateLabel: "Business started date",
        websiteLabel: "Website",
        emailLabel: "Email",
        addImagesLabel: "Upload images",
        addressLabel: "Address",
        mobilePhoneLabel: "Mobile phone",
        phoneLabel: "Phone",
        workTimeLabel: "Work time",
        addWorkTimeLabel: "Add new time range",
        dayLabel: "Day",
        selectDayLabel: "Select day",
        timeRangeLabel: "Time range",
        startTimeRangeLabel: "Start time",
        endTimeRangeLabel: "End time",
    }
}

export default content;